openapi: 3.0.0
tags:
  - name: policy
  - name: commanding
  - name: Business Time
info:
  title: InsurancePolicy
  version: '1.0'
  contact:
    name: Andrey
    email: andrey@covergo.com
  license:
    name: MIT
  description: API for communicating with Insurance Policy domain
servers:
  - url: 'http://localhost:3000'
paths:
  /policy:
    get:
      summary: Your GET endpoint
      tags:
        - policy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyStates'
              examples:
                example-1:
                  value:
                    - issued: true
                      duration: null
                      issueDate: '2019-08-24T14:15:22Z'
                      expiryDate: null
                      isExpired: true
                      amount: 0
                      businessTime: '2019-08-24T14:15:22Z'
      operationId: get-policy
      parameters: []
      security:
        - AccessToken: []
      description: Returns the list of existing policies
    post:
      tags:
        - policy
      summary: ''
      operationId: post-policy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyId'
              examples:
                example-1:
                  value: string
        '400':
          description: Bad Request
      description: 'Create a new policy. If successfull, will return id of created policy.'
      parameters: []
  '/policy/{policyId}':
    parameters:
      - schema:
          type: string
        name: policyId
        in: path
        required: true
        description: id of the policy for the operation
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyState'
        '404':
          description: Not Found
      operationId: get-policy-policyId
      description: Get a specific insurance policy by id
      parameters: []
  '/policy/{policyId}/issuance':
    parameters:
      - schema:
          type: string
        name: policyId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IssuanceRequestStatus'
        '404':
          description: Not Found
      operationId: get-policy-policyId-state
      description: 'Get the information about this policy issuance requests '
    post:
      summary: ''
      operationId: post-policy-policyId-issuance
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
      description: 'Issue target policy. Issue intent id will be generated and returned. '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssuanceRequest'
  '/policy/{policyId}/issuance/{issuanceId}':
    parameters:
      - schema:
          type: string
        name: policyId
        in: path
        required: true
      - schema:
          type: string
        name: issuanceId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssuanceRequestStatus'
        '404':
          description: Not Found
      operationId: get-policy-policyId-issuance-issuanceId
      description: Get status of an issuance request
  '/policy/{policyId}/configurations':
    parameters:
      - schema:
          type: string
        name: policyId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - commanding
      responses: {}
      operationId: get-policy-policyId-configurations
      description: Get information about configurations happend to a policy
    post:
      summary: ''
      operationId: post-policy-policyId-configurations
      responses:
        '200':
          description: OK
      description: Raise new configuration request
  '/policy/{policyId}/configurations/{configurationId}':
    parameters:
      - schema:
          type: string
        name: policyId
        in: path
        required: true
      - schema:
          type: string
        name: configurationId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-policy-policyId-configurations-configurationId
      description: Get information about a configuration request
  '/policy/{policyId}/businesstime/':
    parameters:
      - schema:
          type: string
        name: policyId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - Business Time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessTime'
        '404':
          description: Not Found
      operationId: get-policy-policyId-businesstime
      description: Get business time of the policy
      parameters:
        - schema:
            type: string
          in: query
          name: policyId
    post:
      summary: ''
      operationId: postpolicy-policyId-businesstime
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
        '404':
          description: Not Found
      description: 'Set the businees time of the policy. Needs additional permission. '
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessTime'
      tags:
        - Business Time
  '/policy/{policyId}/businesstime/{time}':
    parameters:
      - schema:
          type: string
        name: policyId
        in: path
        required: true
      - schema:
          type: string
        name: time
        in: path
        required: true
  '/policy/{policyId}/claim':
    parameters:
      - schema:
          type: string
        name: policyId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-policy-policyId-claims
      description: |
        Get a list of claims submitted for this policy
    post:
      summary: ''
      operationId: post-policy-policyId-claim
      responses:
        '200':
          description: OK
      description: Fill a new claim against policy
  '/policy/{policyId}/claim/{claimId}':
    parameters:
      - schema:
          type: string
        name: policyId
        in: path
        required: true
      - schema:
          type: string
        name: claimId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-policy-policyId-claim-claimId
      description: Gets information about a specified claim submitted for this policy
components:
  schemas:
    PolicyState:
      description: State of an insurance policy
      type: object
      title: ''
      properties:
        issued:
          type: boolean
        duration:
          type: string
          nullable: true
          default: 'null'
          format: date-time
        issueDate:
          type:
            - string
            - 'null'
          minLength: 1
          default: 'null'
          format: date-time
        expiryDate:
          type:
            - string
            - 'null'
          format: date-time
          default: 'null'
        isExpired:
          type: boolean
        amount:
          type: number
        businessTime:
          type: string
          minLength: 1
      required:
        - issued
        - issueDate
        - isExpired
        - amount
        - businessTime
    PolicyStates:
      title: PolicyStates
      type: array
      items:
        $ref: '#/components/schemas/PolicyState'
    PolicyId:
      title: PolicyId
      type: string
      description: 'Id of a Policy, must be unique'
    Amount:
      type: integer
      title: Amount
      description: 'Maximum money amount this policy can cover, in USD cents'
      format: int32
      minimum: 1
    Duration:
      title: Duration
      type: object
      description: 'Duration of the policy, in seconds'
      properties:
        id:
          type: integer
          minimum: 1
          format: int64
    IssuanceRequest:
      title: IssuanceRequest
      type: object
      description: 'A request to issue a policy at given time. '
      properties:
        policyId:
          type: string
        issueTime:
          type:
            - string
            - 'null'
          format: date-time
          default: 'null'
          description: |
            Time when policy should be issued. Can be null for immediate issue or a moment in the future
    RequestStatus:
      title: RequestStatus
      type: object
      description: ''
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/RequestStatus'
        error:
          type:
            - string
            - 'null'
    RequestState:
      type: string
      title: RequestState
      enum:
        - pending
        - received
        - processing
        - completed
        - rejected
      default: pending
      description: 'Status of a request sent  '
    BusinessTime:
      type: string
      title: BusinessTime
      format: date-time
      description: ''
  securitySchemes:
    AccessToken:
      name: API Key
      type: apiKey
      in: header
security:
  - AccessToken: []
